# Copyright (c) [2022] Huawei Technologies Co.,Ltd.ALL rights reserved.
# You can use it according to the terms and conditions of the Mulan PSL v2.
#          http://license.coscl.org.cn/MulanPSL2
# THIS PROGRAM IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# Part of codes were generated by scrapy startproject
####################################
# @Author  : Ethan-Zhang
# @email   : ethanzhang55@outlook.com
# @Date    : 2022/08/10 14:13:00
# @License : Mulan PSL v2
#####################################

from pydantic import BaseModel


class OpenqaHomeItem(BaseModel):
    product_name: str
    group_overview_url: str


class OpenqaGroupOverviewItem(BaseModel):
    product_name: str

    build_name: str
    build_time: str
    build_tests_url: str


class OpenqaTestsOverviewItem(BaseModel):
    product_build: str
    test: str

    aarch64_res_status: str
    aarch64_res_log: str
    aarch64_failedmodule_name: str
    aarch64_failedmodule_log: str
    aarch64_start_time: str
    aarch64_end_name: str
    aarch64_test_duration: str

    x86_64_res_status: str
    x86_64_res_log: str
    x86_64_failedmodule_name: str
    x86_64_failedmodule_log: str
    x86_64_start_time: str
    x86_64_end_name: str
    x86_64_test_duration: str
