- alias: 更新baselinetemplate
  uri: /api/v1/baseline-template/{baseline_template_id}
  act: put
- alias: 删除baselinetemplate
  uri: /api/v1/baseline-template/{baseline_template_id}
  act: delete
- alias: 清空指定的基线模板
  uri: /api/v1/baseline-template/{baseline_template_id}/clean
  act: delete
- alias: 基线模板下添加节点
  uri: /api/v1/baseline-template/{baseline_template_id}/base-node
  act: post

