- alias: 获取组织下团队信息
  uri: /api/v1/org/{org_id}/groups
  act: get
- alias: 用户-组织角色绑定
  uri: /api/v1/user-role/org/{org_id}
  act: post
- alias: 用户-组织角色解绑
  uri: /api/v1/user-role/org/{org_id}
  act: delete
- alias: scope-组织角色绑定
  uri: /api/v1/scope-role/org/{org_id}
  act: post
- alias: scope-组织角色解绑
  uri: /api/v1/scope-role/org/{org_id}
  act: delete
- alias: 创建组织角色
  uri: /api/v1/role
  act: post