"""empty message

Revision ID: 6b942fc72432
Revises: e5c52fac5647
Create Date: 2021-12-20 14:09:05.447727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b942fc72432'
down_revision = 'e5c52fac5647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vmachine', sa.Column('special_device', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vmachine', 'special_device')
    # ### end Alembic commands ###
