"""empty message

Revision ID: 7b882cba4552
Revises: a33e732e9853
Create Date: 2021-11-28 18:38:05.015599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b882cba4552'
down_revision = 'a33e732e9853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('frame', sa.Enum('aarch64', 'x86_64'), nullable=False))
    op.add_column('task', sa.Column('automatic', sa.Boolean(), nullable=False))
    op.add_column('task_milestone', sa.Column('job_result', sa.Enum('block', 'done', 'running', 'pending'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_milestone', 'job_result')
    op.drop_column('task', 'automatic')
    op.drop_column('task', 'frame')
    # ### end Alembic commands ###
