"""empty message

Revision ID: a33e732e9853
Revises: fcdc7194e426
Create Date: 2021-11-27 11:42:49.896969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33e732e9853'
down_revision = 'fcdc7194e426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('owner', sa.String(length=64), nullable=True))
    op.add_column('suite', sa.Column('owner', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suite', 'owner')
    op.drop_column('case', 'owner')
    # ### end Alembic commands ###
