"""empty message

Revision ID: bf94bba5a25c
Revises: 7b882cba4552
Create Date: 2021-12-03 15:45:12.137045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf94bba5a25c'
down_revision = '7b882cba4552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case', 'preset',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case', 'preset',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    # ### end Alembic commands ###
