"""empty message

Revision ID: e5c52fac5647
Revises: 362cc4ba7466
Create Date: 2021-12-16 11:22:56.572155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c52fac5647'
down_revision = '362cc4ba7466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('mode', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'mode')
    # ### end Alembic commands ###
