"""empty message

Revision ID: ed39b60f18bc
Revises: ac1eeafabce9
Create Date: 2021-12-15 16:11:06.938313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed39b60f18bc'
down_revision = 'ac1eeafabce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_name'), table_name='job')
    # ### end Alembic commands ###
