"""empty message

Revision ID: f1236809550c
Revises: 
Create Date: 2021-11-25 19:31:52.970826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1236809550c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('log_url', table_name='analyzed')
    op.add_column('task_milestone', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_milestone', 'template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_milestone', type_='foreignkey')
    op.drop_column('task_milestone', 'template_id')
    op.create_index('log_url', 'analyzed', ['log_url'], unique=False)
    # ### end Alembic commands ###
