"""empty message

Revision ID: fcdc7194e426
Revises: 77ad97b8ecde
Create Date: 2021-11-26 15:57:28.562353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdc7194e426'
down_revision = '77ad97b8ecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pmachine', sa.Column('occupier', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pmachine', 'occupier')
    # ### end Alembic commands ###
