# Copyright (c) [2022] Huawei Technologies Co.,Ltd.ALL rights reserved.
# You can use it according to the terms and conditions of the Mulan PSL v2.
#          http://license.coscl.org.cn/MulanPSL2
# THIS PROGRAM IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# Part of codes were generated by scrapy startproject
####################################
# @Author  : Ethan-Zhang
# @email   : ethanzhang55@outlook.com
# @Date    : 2022/08/10 14:13:00
# @License : Mulan PSL v2
#####################################

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class OpenqaHomeItem(scrapy.Item):
    product_name = scrapy.Field()
    group_overview_url = scrapy.Field()


class OpenqaGroupOverviewItem(scrapy.Item):
    product_name =  scrapy.Field()

    build_name = scrapy.Field()
    build_time = scrapy.Field()
    build_tests_url = scrapy.Field()


class OpenqaTestsOverviewItem(scrapy.Item):
    product_build = scrapy.Field()
    test = scrapy.Field()

    aarch64_res_status = scrapy.Field()
    aarch64_res_log = scrapy.Field()
    aarch64_failedmodule_name = scrapy.Field()
    aarch64_failedmodule_log = scrapy.Field()
    aarch64_start_time = scrapy.Field()
    aarch64_end_name = scrapy.Field()
    aarch64_test_duration = scrapy.Field()

    x86_64_res_status = scrapy.Field()
    x86_64_res_log = scrapy.Field()
    x86_64_failedmodule_name = scrapy.Field()
    x86_64_failedmodule_log = scrapy.Field()
    x86_64_start_time = scrapy.Field()
    x86_64_end_name = scrapy.Field()
    x86_64_test_duration = scrapy.Field()
    

class OpeneulerPkgsListItem(scrapy.Item):
    rpm_file_name = scrapy.Field()
    build = scrapy.Field()
    product = scrapy.Field()
    repo_path = scrapy.Field()
    arch = scrapy.Field()
    round = scrapy.Field()